all:
	mv pspnet_adhoc_matching.prx ../dist/kd/pspnet_adhoc_matching.prx

TARGET = pspnet_adhoc_matching

LIBRARYOBJS = \
library/functions.o \
library/calls/init.o \
library/calls/term.o \
library/calls/create.o \
library/calls/start.o \
library/calls/stop.o \
library/calls/delete.o \
library/calls/select.o \
library/calls/cancel.o \
library/calls/send.o \
library/calls/abortsend.o \
library/calls/sethello.o \
library/calls/gethello.o \
library/calls/getmembers.o \
library/calls/getpoolmaxalloc.o \
library/calls/getpoolstat.o

IMPORTS = \
imports/sceNetAdhoc.o

OBJS = main.o ../memab/ATPRO.o $(LIBRARYOBJS) $(IMPORTS)

CFLAGS = -Os -G0 -Wall -fno-pic

ifeq ($(CONFIG_620), 1)
CFLAGS += -DCONFIG_620=1
endif

ifeq ($(CONFIG_63X), 1)
CFLAGS += -DCONFIG_63X=1
endif

ifeq ($(CONFIG_660), 1)
CFLAGS += -DCONFIG_660=1
endif

ifeq ($(RELEASE), 1)
CFLAGS += -DRELEASE=1
else
CFLAGS += -DDEBUG=1
endif

ifeq ($(TRACE), 1)
CFLAGS += -DTRACE=1
endif

CXXFLAGS = $(CFLAGS) -fno-exceptions -fno-rtti
ASFLAGS = $(CFLAGS)

BUILD_PRX = 1
PRX_EXPORTS = exports.exp

USE_PSPSDK_LIBC = 1

LDFLAGS = -mno-crt0 -nostartfiles

PSPSDK=$(shell psp-config --pspsdk-path)
include $(PSPSDK)/lib/build.mak
